permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: 李大饼
  email: liyibing28@gmail.com
  link: http://liyibing28.github.io
#  weibo: http://weibo.com/orangeissweet
  github: http://github.com/liyibing28
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 李大饼的博客
description: My personal blog
url: http://liyibing28.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/header.jpg
favicon: /public/img/header.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - PC
  - English

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档